spring.datasource.url=jdbc:mysql://localhost:3306/db_bingofacil?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub

aws.s3.bucket-name=bucket-bingo-facil
aws.s3.endpoint=http://localhost:9000
aws.s3.region=us-east-1
